a

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,13 +14,9 @@ on:
       - terraform/**
 
 env:
-  # Credentials for deployment
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  
-  # S3 bucket to store TF state
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
-
   AWS_REGION: us-east-2
   EKS_CLUSTER: appiac-eks
 
@@ -55,6 +51,13 @@ jobs:
         id: plan
         run: terraform plan -no-color -input=false -out planfile
         continue-on-error: true
+
+      - name: Show terraform plan output on failure
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "Terraform Plan Failed"
+          tail -n 20 .terraform/planfile  # Print last 20 lines of the plan file
+          exit 1
 
       - name: Terraform plan status
         if: steps.plan.outcome == 'failure'
